	Computer_System u0 (
		.gyro_sda_in                                        (<connected-to-gyro_sda_in>),                                        //                                       gyro.sda_in
		.gyro_scl_in                                        (<connected-to-gyro_scl_in>),                                        //                                           .scl_in
		.gyro_sda_oe                                        (<connected-to-gyro_sda_oe>),                                        //                                           .sda_oe
		.gyro_scl_oe                                        (<connected-to-gyro_scl_oe>),                                        //                                           .scl_oe
		.hex3_hex0_export                                   (<connected-to-hex3_hex0_export>),                                   //                                  hex3_hex0.export
		.hex5_hex4_export                                   (<connected-to-hex5_hex4_export>),                                   //                                  hex5_hex4.export
		.joyirq_ext_export                                  (<connected-to-joyirq_ext_export>),                                  //                                 joyirq_ext.export
		.leds_export                                        (<connected-to-leds_export>),                                        //                                       leds.export
		.penirq_n_export                                    (<connected-to-penirq_n_export>),                                    //                                   penirq_n.export
		.pushbuttons_export                                 (<connected-to-pushbuttons_export>),                                 //                                pushbuttons.export
		.pwmx_conduit_clk                                   (<connected-to-pwmx_conduit_clk>),                                   //                               pwmx_conduit.clk
		.pwmx_conduit_pwm                                   (<connected-to-pwmx_conduit_pwm>),                                   //                                           .pwm
		.pwmy_conduit_clk                                   (<connected-to-pwmy_conduit_clk>),                                   //                               pwmy_conduit.clk
		.pwmy_conduit_pwm                                   (<connected-to-pwmy_conduit_pwm>),                                   //                                           .pwm
		.sdram_addr                                         (<connected-to-sdram_addr>),                                         //                                      sdram.addr
		.sdram_ba                                           (<connected-to-sdram_ba>),                                           //                                           .ba
		.sdram_cas_n                                        (<connected-to-sdram_cas_n>),                                        //                                           .cas_n
		.sdram_cke                                          (<connected-to-sdram_cke>),                                          //                                           .cke
		.sdram_cs_n                                         (<connected-to-sdram_cs_n>),                                         //                                           .cs_n
		.sdram_dq                                           (<connected-to-sdram_dq>),                                           //                                           .dq
		.sdram_dqm                                          (<connected-to-sdram_dqm>),                                          //                                           .dqm
		.sdram_ras_n                                        (<connected-to-sdram_ras_n>),                                        //                                           .ras_n
		.sdram_we_n                                         (<connected-to-sdram_we_n>),                                         //                                           .we_n
		.sdram_clk_clk                                      (<connected-to-sdram_clk_clk>),                                      //                                  sdram_clk.clk
		.slider_switches_export                             (<connected-to-slider_switches_export>),                             //                            slider_switches.export
		.system_pll_ref_clk_clk                             (<connected-to-system_pll_ref_clk_clk>),                             //                         system_pll_ref_clk.clk
		.system_pll_ref_reset_reset                         (<connected-to-system_pll_ref_reset_reset>),                         //                       system_pll_ref_reset.reset
		.touch_spi_MISO                                     (<connected-to-touch_spi_MISO>),                                     //                                  touch_spi.MISO
		.touch_spi_MOSI                                     (<connected-to-touch_spi_MOSI>),                                     //                                           .MOSI
		.touch_spi_SCLK                                     (<connected-to-touch_spi_SCLK>),                                     //                                           .SCLK
		.touch_spi_SS_n                                     (<connected-to-touch_spi_SS_n>),                                     //                                           .SS_n
		.video_lt24_controller_0_external_interface_lcd_on  (<connected-to-video_lt24_controller_0_external_interface_lcd_on>),  // video_lt24_controller_0_external_interface.lcd_on
		.video_lt24_controller_0_external_interface_reset_n (<connected-to-video_lt24_controller_0_external_interface_reset_n>), //                                           .reset_n
		.video_lt24_controller_0_external_interface_csx     (<connected-to-video_lt24_controller_0_external_interface_csx>),     //                                           .csx
		.video_lt24_controller_0_external_interface_data    (<connected-to-video_lt24_controller_0_external_interface_data>),    //                                           .data
		.video_lt24_controller_0_external_interface_rdx     (<connected-to-video_lt24_controller_0_external_interface_rdx>),     //                                           .rdx
		.video_lt24_controller_0_external_interface_wrx     (<connected-to-video_lt24_controller_0_external_interface_wrx>),     //                                           .wrx
		.video_lt24_controller_0_external_interface_dcx     (<connected-to-video_lt24_controller_0_external_interface_dcx>),     //                                           .dcx
		.video_pll_0_ref_clk_clk                            (<connected-to-video_pll_0_ref_clk_clk>),                            //                        video_pll_0_ref_clk.clk
		.video_pll_0_ref_reset_reset                        (<connected-to-video_pll_0_ref_reset_reset>),                        //                      video_pll_0_ref_reset.reset
		.vga_CLK                                            (<connected-to-vga_CLK>),                                            //                                        vga.CLK
		.vga_HS                                             (<connected-to-vga_HS>),                                             //                                           .HS
		.vga_VS                                             (<connected-to-vga_VS>),                                             //                                           .VS
		.vga_BLANK                                          (<connected-to-vga_BLANK>),                                          //                                           .BLANK
		.vga_SYNC                                           (<connected-to-vga_SYNC>),                                           //                                           .SYNC
		.vga_R                                              (<connected-to-vga_R>),                                              //                                           .R
		.vga_G                                              (<connected-to-vga_G>),                                              //                                           .G
		.vga_B                                              (<connected-to-vga_B>)                                               //                                           .B
	);

